# Generated by Django 5.1.2 on 2024-12-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('belum diproses', 'Belum Diproses'), ('sedang diproses', 'Sedang Diproses'), ('selesai', 'Selesai')], max_length=50)),
                ('menu', models.ManyToManyField(to='api.menu')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('kartu', 'Kartu'), ('gopay', 'GoPay')], max_length=50)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('pemesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pemesanan')),
            ],
        ),
    ]
